run:
	gcc -c -o cube.o cube.c 
	gcc -o cube.exe cube.o -lglu32 -lfreeglut -lopengl32 -Wl,--subsystem,windows

clean:
	rm *.o
	rm *.exe
ocube:
	gcc -c -o ocube.o ocube.c 
	gcc -o ocube.exe ocube.o -lglu32 -lfreeglut -lopengl32 -Wl,--subsystem,windows
