getMaxTexture:
	gcc -c -o getMaxTexture.o getMaxTexture.cpp 
	gcc -o getMaxTexture.exe getMaxTexture.o -lfreeglut -lopengl32 -lglu32 -Wl,--subsystem,windows

clean:
	rm *.o
	rm *.exe

getGLVersion:
	g++ -c -o getGLVersion.o getGLVersion.cpp 
	g++ -o getGLVersion.exe getGLVersion.o -lfreeglut -lopengl32 -lglu32 -Wl,--subsystem,windows
